- name: Start Spark Node
  template:
    src: spark-worker.service
    dest: /etc/systemd/system/spark-node.service
    mode: 755
    force: yes

- name: Force systemd to reread configs
  systemd: 
    daemon_reload: yes

- name: Start Spark Node
  systemd: 
    name: spark-node
    state: restarted 
    enabled: yes