- name: Install Spark Master Service
  template:
    src: spark-master.service
    dest: /etc/systemd/system/spark-master.service
    mode: 755
    force: yes

- name: Force systemd to reread configs
  systemd: 
    daemon_reload: yes

- name: Start Spark Master
  systemd: 
    name: spark-master
    state: restarted 
    enabled: yes